#define MASS_ELECTRON 9.11E-31
#define CHARGE_ELECTRON -1.6E-19

#define MASS_PROTON 1.67E-37
#define CHARGE_PROTON -CHARGE_ELECTRON

#define MASS_ALPHA 4*MASS_PROTON
#define CHARGE_ALPHA -4*CHARGE_PROTON
#define V_RUTHERFORD_ALPHA 1E7

#define MASS_GOLD_NUCLEUS 197*MASS_PROTON
#define CHARGE_GOLD_NUCLEUS 197*CHARGE_PROTON
